### ISSUE TITLE
game visualization 

### ISSUE THREAD

**Issue by nanxintin** [facebookresearch/CommNet#2]
Hi, 
Very meaningful work and thank you for opening the code.
I was wondering how to make the game visualization during training or test? Just as the Figure 2 shown in your paper.  I tried the "test()". and it did not work.
Do I need to install the MazeBase or something else?

**Comment by tesatory** [comment]
that's weird. Are you sure It is not printing the game play in console? this is the code that prints the map https://github.com/facebookresearch/CommNet/blob/d7450fc3cd336119ea5bf970a0db1added65d2ca/train.lua#L108

**Comment by YidingYu** [comment]
th -i flag will keep torch alive
add -i in the train script samples,  e.g.,
th main.lua --lrate 0.003 --model lstm --games_config_path games/config/crossing_easy.lua \
--nagents 5 --max_steps 20 --nactions 2 --curriculum_sta 10 --curriculum_end 40 --comm \
--visibility 0 --show --epochs 50 --show -i
then run test()

**Comment by nanxintin** [comment]
@Martin729 Thanks for your reply.
When I tried your solution, it output an error "invalid argument: -i".
It was weird. Could you give me some advice?

**Comment by tesatory** [comment]
you should add "-i" after "th" but before "main.lua". Like this "th -i main.lua ..."

**Comment by nanxintin** [comment]
@tesatory Thanks for your help, it works.
